spring.application.name=Movie_APIGateway

server.port=7000

# =========================
# EUREKA SERVER
# =========================
eureka.client.service-url.defaultZone=http://localhost:8761/eureka


# =========================
# ADMIN MOVIE SERVICE
# =========================
spring.cloud.gateway.server.webmvc.routes[0].id=movie-service

spring.cloud.gateway.server.webmvc.routes[0].uri=lb://MOVIE-SERVICE

spring.cloud.gateway.server.webmvc.routes[0].predicates[0]=Path=/admin/movies/**


# =========================
# USER MOVIE SERVICE
# =========================
spring.cloud.gateway.server.webmvc.routes[1].id=user-movie-service

spring.cloud.gateway.server.webmvc.routes[1].uri=lb://MOVIE-SERVICE

spring.cloud.gateway.server.webmvc.routes[1].predicates[0]=Path=/users/movies/**

spring.cloud.gateway.server.webmvc.routes[1].order=1


# =========================
# ADMIN BOOKING SERVICE
# =========================
spring.cloud.gateway.server.webmvc.routes[2].id=admin-booking-service

spring.cloud.gateway.server.webmvc.routes[2].uri=lb://MOVIEBOOKINGSERVICE

spring.cloud.gateway.server.webmvc.routes[2].predicates[0]=Path=/admin/booking/**


# =========================
# USER BOOKING SERVICE
# =========================
spring.cloud.gateway.server.webmvc.routes[3].id=user-booking-service

spring.cloud.gateway.server.webmvc.routes[3].uri=lb://MOVIEBOOKINGSERVICE

spring.cloud.gateway.server.webmvc.routes[3].predicates[0]=Path=/user/bookings/**


# =========================
# USER PROFILE SERVICE
# =========================
spring.cloud.gateway.server.webmvc.routes[4].id=user-service

spring.cloud.gateway.server.webmvc.routes[4].uri=lb://MOVIE-USER-SERVICE

spring.cloud.gateway.server.webmvc.routes[4].predicates[0]=Path=/users/profile/**

spring.cloud.gateway.server.webmvc.routes[4].order=10


# =========================
# CORS CONFIGURATION
# =========================
spring.cloud.gateway.server.webmvc.globalcors.cors-configurations.[/**].allowedOrigins=http://localhost:3000

spring.cloud.gateway.server.webmvc.globalcors.cors-configurations.[/**].allowedMethods=GET,POST,PUT,DELETE,OPTIONS

spring.cloud.gateway.server.webmvc.globalcors.cors-configurations.[/**].allowedHeaders=*







