spring.application.name=Movie_APIGateway


server.port=7000

eureka.client.service-url.defaultZone=http://localhost:8761/eureka



# Gateway Route - Movie Service
spring.cloud.gateway.server.webmvc.routes[0].id=movie-service
spring.cloud.gateway.server.webmvc.routes[0].uri=lb://MOVIE-SERVICE
spring.cloud.gateway.server.webmvc.routes[0].predicates[0]=Path=/movies/**



# User Service
spring.cloud.gateway.server.webmvc.routes[1].id=user-service
spring.cloud.gateway.server.webmvc.routes[1].uri=lb://MOVIE-USER-SERVICE
spring.cloud.gateway.server.webmvc.routes[1].predicates[0]=Path=/users/**


# Booking Service
spring.cloud.gateway.server.webmvc.routes[2].id=user-service
spring.cloud.gateway.server.webmvc.routes[2].uri=lb://MovieBookingService
spring.cloud.gateway.server.webmvc.routes[2].predicates[0]=Path=/bookings/**